### ISSUE TITLE
ImportError: cannot import name 'TessQuickLook' from 'tql'

### ISSUE THREAD

**Issue by JosephKarpinski** [jpdeleon/quicklook#1]
macOS Sonoma 14.2.1 

VSCode
Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:57.520Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

See below attachments:

![Screenshot 2024-03-18 at 9 37 10 AM](https://github.com/jpdeleon/quicklook/assets/37123616/07e05b89-e6d4-41c6-92d8-9ace3272f266)
![Screenshot 2024-03-18 at 9 37 55 AM](https://github.com/jpdeleon/quicklook/assets/37123616/e9241f07-b07a-4d19-b805-49fecf6dab55)
![Screenshot 2024-03-18 at 9 38 23 AM](https://github.com/jpdeleon/quicklook/assets/37123616/aaaa50aa-faa1-47ac-a48a-448b995538c7)
![Screenshot 2024-03-18 at 9 38 52 AM](https://github.com/jpdeleon/quicklook/assets/37123616/843ac693-2dd2-45cc-bfca-9cc7a0934817)
![Screenshot 2024-03-18 at 9 39 26 AM](https://github.com/jpdeleon/quicklook/assets/37123616/eb8ab653-3d85-48ce-a7fb-754ea1b0621d)
![Screenshot 2024-03-18 at 9 41 54 AM](https://github.com/jpdeleon/quicklook/assets/37123616/a6b3c0a1-89a3-4f75-8184-d068a6507a35)
![Screenshot 2024-03-18 at 9 44 13 AM](https://github.com/jpdeleon/quicklook/assets/37123616/411d78ab-dd3d-437a-9798-888ab23ae956)

**Comment by JosephKarpinski** [comment]
Running under Jupyter Lab:

![Screenshot 2024-03-18 at 9 55 11 AM](https://github.com/jpdeleon/quicklook/assets/37123616/3cc5e98a-9eb2-4496-9bdd-9198ade2af9b)

**Comment by JosephKarpinski** [comment]
Command line:

josephkarpinski@Josephs-iMac-2 ~ % conda activate envQuicklook                                                               
(envQuicklook) josephkarpinski@Josephs-iMac-2 ~ % ql -name TOI-241 -img      
zsh: illegal hardware instruction  ql -name TOI-241 -img
(envQuicklook) josephkarpinski@Josephs-iMac-2 ~ % /Users/josephkarpinski/opt/anaconda3/envs/envQuicklook/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by jpdeleon** [comment]
Hi @JosephKarpinski thanks for using quicklook. It seems you are using the old version of the tutorial. Can you pull the most recent version?

You can check if you local copy is identical to the tutorial here: https://github.com/jpdeleon/quicklook/blob/main/notebook/examples.ipynb

**Comment by JosephKarpinski** [comment]
Still have issues running on M1 iMac Jupiter Lab

![Screenshot 2024-03-19 at 10 37 24 AM](https://github.com/jpdeleon/quicklook/assets/37123616/30a8891c-56fd-43de-bab9-d4477feeb1b6)

Runs fine on Intel iMac Monterey in Jupiter Lab
Intel VSCode code have numpy.int depreciated errors that are not caught in Jupiter Lab

**Comment by JosephKarpinski** [comment]
Conda installed newest quicklook package on my M1 iMac Sonoma 14.2.1 (23C71)
Same error.

(base) josephkarpinski@Josephs-iMac-2 ~ % conda activate envQuicklook4
(envQuicklook4) josephkarpinski@Josephs-iMac-2 ~ % cd /Users/josephkarpinski/Downloads/quicklook-main-3/scripts/
(envQuicklook4) josephkarpinski@Josephs-iMac-2 scripts % ./ql -name "TIC283015592"                                    
zsh: illegal hardware instruction  ./ql -name "TIC283015592"
(envQuicklook4) josephkarpinski@Josephs-iMac-2 scripts % /Users/josephkarpinski/opt/anaconda3/envs/envQuicklook4/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

Is there a verbose switch or debug option that can pinpoint the failing line of code?

**Comment by jpdeleon** [comment]
This is a Mac specific issue and I'm working on it. I'll update here as soon as I find a fix :)

**Comment by jpdeleon** [comment]
I tested macos-14 and it seems to work now. Can you try again?

You can update your installation to version 1.1 by running: 
`pip install -e git+https://github.com/jpdeleon/quicklook.git#egg=quicklook`

**Comment by JosephKarpinski** [comment]
Resolved under latest update.
