### ISSUE TITLE
Time of Day Issue: Working on Intel iMac Monterey, Stopped working, Now Working Again

### ISSUE THREAD

**Issue by JosephKarpinski** [jpdeleon/quicklook#2]
7 PM EST time working. 
All day not working.
Time of day issue?

Lots of different errors.
New Conda installs multiple times, 
Same errors,
Now working.

<img width="1372" alt="Screen Shot 2024-03-19 at 11 05 06 AM" src="https://github.com/jpdeleon/quicklook/assets/37123616/8a92bb88-93ff-443d-872a-e644763596ef">

<img width="1372" alt="Screen Shot 2024-03-19 at 11 05 29 AM" src="https://github.com/jpdeleon/quicklook/assets/37123616/b7e24475-d596-4502-a529-a528baa91433">

<img width="1372" alt="Screen Shot 2024-03-19 at 12 37 27 PM" src="https://github.com/jpdeleon/quicklook/assets/37123616/de6d22b5-203f-4838-bd5e-d9a12bb840ac">

<img width="1372" alt="Screen Shot 2024-03-19 at 1 12 13 PM" src="https://github.com/jpdeleon/quicklook/assets/37123616/5a3bab06-6fff-4f05-a3cf-b90192f97228">

<img width="1372" alt="Screen Shot 2024-03-19 at 1 40 42 PM" src="https://github.com/jpdeleon/quicklook/assets/37123616/f7c65755-5bff-4cf9-9c44-fc61c17010ac">

<img width="1372" alt="Screen Shot 2024-03-19 at 1 40 59 PM" src="https://github.com/jpdeleon/quicklook/assets/37123616/7bfb4861-1817-42fc-82a3-df6a89bc545c">

<img width="1131" alt="Screen Shot 2024-03-19 at 2 11 42 PM" src="https://github.com/jpdeleon/quicklook/assets/37123616/5ed31a76-9274-49d0-b793-26604b0c048f">

<img width="1002" alt="Screen Shot 2024-03-19 at 2 17 26 PM" src="https://github.com/jpdeleon/quicklook/assets/37123616/56a993aa-ac4b-46d3-9315-c23c5ff5cebf">

<img width="1002" alt="Screen Shot 2024-03-19 at 2 33 06 PM" src="https://github.com/jpdeleon/quicklook/assets/37123616/4e8f0441-6952-439b-8f78-b84c09dfad8a">

**Comment by jpdeleon** [comment]
It seems your environment throws different errors, one is related to using a deprecated function (`numpy.int`) in an old version of numpy and the other has to do with external websites queried by `quicklook` which is temporarily down. For the meantime, I will setup comprehensive tests for Mac environments to catch and prevent these errors.

**Comment by jpdeleon** [comment]
This is a Mac specific issue and I'm working on it. I'll update here as soon as I find a fix :)

**Comment by jpdeleon** [comment]
This is a Mac specific issue and I'm working on it. I'll update here as soon as I find a fix :)

**Comment by jpdeleon** [comment]
Can you also check if this error still occurs?

**Comment by JosephKarpinski** [comment]
Appears to be working fine now. Closing.
