### ISSUE TITLE
ValueError cannot convert float NaN to internet 

### ISSUE THREAD

**Issue by JosephKarpinski** [jpdeleon/quicklook#3]
About 50% of this target set of TIC identifiers get "ValueError cannot convert float NaN to internet"

[21113347,
 36718161,
 71854732,
 72504752,
 80713983,
 97700520,
 107782586,
 110428269,
 112026224,
 124709665,
 125442121,
 127328218,
 139853601,
 140706664,
 181304295,
 191998744,
 200917197,
 220547837,
 235300016,
 239628993,
 240613164,
 245392284,
 250724252,
 264912889,
 272211398,
 272219353,
 275758701,
 283015592,
 295354126,
 304426002,
 312259170,
 314013231,
 319068154,
 320994166,
 324395151,
 325172035]

<img width="1083" alt="ValueError cannot convert float NaN to integer" src="https://github.com/jpdeleon/quicklook/assets/37123616/94c362fc-2954-4774-a1fc-56020cba2648">

**Comment by jpdeleon** [comment]
Ah good catch! This error has to do with some stars having unknown stellar parameters. I'll deploy a fix soon.

**Comment by jpdeleon** [comment]
This issue has now been resolved. Make sure you use quicklook version 1.0.1.
