### ISSUE TITLE
AssertionError: author=SPOC not in {'QLP'}

### ISSUE THREAD

**Issue by JosephKarpinski** [jpdeleon/quicklook#5]
This happens a lot:

Generating TQL for TIC 219519705...
All available lightcurves:
  author         mission  t_exptime
0    QLP  TESS Sector 51      600.0
1    QLP  TESS Sector 52      600.0
Available sectors: [51, 52]
Traceback (most recent call last):
  File "/Users/josephkarpinski/Downloads/quicklook-main/scripts/./ql", line 225, in <module>
    ql = TessQuickLook(
  File "/Users/josephkarpinski/src/quicklook/quicklook/tql.py", line 117, in __init__
    self.raw_lc = self.get_lc(
  File "/Users/josephkarpinski/src/quicklook/quicklook/tql.py", line 316, in get_lc
    assert kwargs.get("author").upper() in all_authors, err_msg
AssertionError: author=SPOC not in {'QLP'}

![Screenshot 2024-03-24 at 11 52 03 AM](https://github.com/jpdeleon/quicklook/assets/37123616/e2d931df-86a1-4931-95fa-5a8ec6906df8)

![Screenshot 2024-03-24 at 11 53 46 AM](https://github.com/jpdeleon/quicklook/assets/37123616/2e97a5c8-4616-4089-b66a-6bfdeb19fe5c)

**Comment by JosephKarpinski** [comment]
More data

![Screenshot 2024-03-24 at 11 58 52 AM](https://github.com/jpdeleon/quicklook/assets/37123616/03da9354-7c07-4e6b-8900-207226aa6485)

**Comment by JosephKarpinski** [comment]
More data:

<img width="1103" alt="Assertive Error" src="https://github.com/jpdeleon/quicklook/assets/37123616/01de7c58-c904-4d55-8dbf-285c8f98fc64">

**Comment by jpdeleon** [comment]
Ah, the lightcurve reduced by the default pipeline (SPOC) is not available for this target. So you can simply set `pipeline="QLP"`.

QLP light curves have shorter cadence typically 10 or 30 minutes than SPOC light curves with cadence of 2 minutes or shorter.

**Comment by JosephKarpinski** [comment]
That worked!
Thank you!

Closing....
